low = [
    ("pornhub.com",),
    ("www.pornhub.com",),
    ("xnxx.com",),
    ("www.xnxx.com",),
    ("xvideos.com",),
    ("www.xvideos.com",),
    ("sex.com",),
    ("www.sex.com",),
    ("api.likee.video",),
    ("googll.store",),
    ("onlyfans.com",),
    ("lustery.com",),
    ("ei.phcdn.com",),
    ("ew.phcdn.com",),
    ("ss.phcdn.com",),
    ("em-h.phcdn.com",),
    ("cdn1d-static-shared.phcdn.com",),
    ("cdn1-smallimg.phcdn.com",),
    ("xhamster.com",),
    ("www.xhamster.com",),
    ("xvideos-ar.com",),
    ("stripchat.com",),
    ("ar.stripchat.com",),
    ("go.stripchat.com",),
    ("www.xvideos-ar.com",),
    ("api.likee.video",),
    ("vast.livejasmin.com",),
    ("media.trafficjunky.net",),
    ("collector.xhamster.com",),
    ("f1cdn.nsimg.net",),
    ("go.sexfortokens.com",),
    ("eic.service.lgtvcommon.com",),
    ("googleads.g.doubleclick.net",),
    ("www.google.com", "216.239.38.120"),
    ("www.youtube.com", "216.239.38.120"),
    ("youtube.com", "216.239.38.120"),
    ("m.youtube.com", "216.239.38.120"),
    ("youtubei.googleapis.com", "216.239.38.120"),
    ("youtube.googleapis.com", "216.239.38.120"),
    ("www.youtube-nocookie.com", "216.239.38.120"),
]
